package framework.wss.pages.productdetail.map

import above.Execute
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapContactUsCommonFunctionality
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapEmail
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapEnterYourEmail
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapLoginOverride
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapLowestPriceGuarantee
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapPriceAndUom
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapQualified
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapRetailPrice
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapStartALiveChatOrPhoneNumber
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtPDPMapZ
import framework.wss.pages.productdetail.map.uniquemapfunctionality.UtQuantityDiscounts

Execute.suite([
        new UtPDPMapContactUsCommonFunctionality(),
        new UtPDPMapEmail(),
        new UtPDPMapEnterYourEmail(),
        new UtPDPMapLowestPriceGuarantee(),
        new UtPDPMapLoginOverride(),
        new UtPDPMapPriceAndUom(),
        new UtPDPMapQualified(),
        new UtPDPMapRetailPrice(),
        new UtPDPMapStartALiveChatOrPhoneNumber(),
        new UtPDPMapZ(),
        new UtQuantityDiscounts(),
/*        new UtPDPMapANotQualified(),
        new UtPDPMapAQualified(),
        new UtPDPMapBNotQualified(),
        new UtPDPMapBQualified(),
        new UtPDPMapCNotQualified(),
        new UtPDPMapDNotQualified(),
        new UtPDPMapDQualified(),
        new UtPDPMapHNotQualified(),
        new UtPDPMapHQualified(),
        new UtPDPMapINotQualified(),
        new UtPDPMapIQualified(),
        new UtPDPMapKNotQualified(),
        new UtPDPMapMNotQualified(),
        new UtPDPMapMQualified(),
        new UtPDPMapNNotQualified(),
        new UtPDPMapNQualified(),
        new UtPDPMapONotQualified(),
        new UtPDPMapONotQualifiedGoogle(),
        new UtPDPMapOQualified(),
        new UtPDPMapOQualifiedGoogle(),
        new UtPDPMapPNotQualified(),
        new UtPDPMapPQualified(),
        new UtPDPMapQNotQualified(),
        new UtPDPMapQQualified(),
        new UtPDPMapSNotQualified(),
        new UtPDPMapSNotQualifiedGoogle(),
        new UtPDPMapSQualified(),
        new UtPDPMapSQualifiedGoogle(),
        new UtPDPMapTNotQualified(),
        new UtPDPMapTQualified(),
        new UtPDPMapVNotQualified(),
        new UtPDPMapWNotQualified(),
        new UtPDPMapWQualified(),
        new UtPDPMapXNotQualified(),
        new UtPDPMapXQualified(),
        new UtPDPMapZNotQualified(),
        new UtPDPMapZQualified(),*/
])
