package above.azure

/**
 * Azure DevOps Projects List 
 * @author akudin
 */

class AzureDevOpsProjects {

	static names = [
		"3D Printer",
		"401k Quiz",
		"AP Inbox",
		"AP Inbox Workflow",
		"AdWordsUpdater",
		"Architecture",
		"Atlas",
		"Automation Projects",
		"AutoReorders",
		"BA Project Manager",
		"BA Sandbox",
		"Benefits",
		"BiometricAuthentication",
		"Blogs",
		"Briefcase",
		"CAMP",
		"Camp .net",
		"Careers",
		"Catalog",
		"Catalog Authoring",
		"C-Sharp Development Guide",
		"CF Shared Components",
		"CFML Development Guide",
		"CFSE Project Administration System",
		"CSP-Payments.clarkinet.com",
		"Carpool",
		"Category Toppers",
		"Change Management",
		"Channel Partners Group",
		"Chat Bot",
		"Clapper",
		"Clark Asset Server Client",
		"Clark Chains",
		"ChatStats",
		"Clark File Mover",
		"Clark Hackathon",
		"Clark.AppFoundations",
		"Clark.Auth",
		"Clark.Configuration",
		"Clark.Coravel",
		"Clark.DatabaseStandards",
		"Clark.Encryption",
		"Clark.FluentMigrator",
		"Clark.Inet",
		"Clark.Logging",
		"Clark.Party",
		"Clark.V8Engine",
		"Clark.V8Engine.Proxies",
		"ClarkAssociates-Payments.clarkinc.biz",
		"Clarkfiguration",
		"Clarkinet API",
		"Coffee Station",
		"Commercial Stainless",
		"Core Site",
		"Core Website",
		"CPG XYZ",
		"CSG Warranty",
		"Customer Service Stats Board",
		"CWC",
		"Dash",
		"Database Standards",
		"DB Tracker",
		"DBA Ticket Project",
		"DbStandardsCheck",
		"Deploy",
		"Deploy Dashboard",
		"Design",
		"Design Documentation",
		"Developer Stats Board",
		"Developer Task Ordering",
		"Disc",
		"EDI",
		"EDI Consumers",
		"Electronic Document Interchange",
		"Employee Resources",
		"Enterprise Data Management",
		"Enterprise Data Warehouse",
		"Enterprise ETL",
		"Enterprise Reporting",
		"Eva",
		"Expressive Annotation - .NET Core",
		"Fedex Ship Manager Server (FSMS)",
		"FedExWarehouseIntegration",
		"Field Service",
		"Flyer Mailer",
		"Food Service Resources",
		"Forum",
		"GoToWebstore",
		"Help Desk Stats",
		"Hometown Provisions Payment Portal",
		"Hood Builder",
		"IDS Consumer Template",
		"IDS.DataContracts",
		"IDS.Mobile",
		"IDS.QueueClient (Mirror)",
		"IT Out of Office",
		"Install Network",
		"Inventory Management",
		"Isaacs",
		"JMeter Load Testing",
		"JavaScript Development Guide",
		"LancasterBBB",
		"LTL",
		"LanguageStats",
		"Logistics - Routing",
		"Logistics Auto Verify",
		"Logistics Fraud-Notifications",
		"Lunch",
		"Mailroom",
		"Marketing Sites Rewrite",
		"Moodle",
		"New Hire Guide",
		"NewItems",
		"NewRelic Instrumentation",
		"Noble Service Request",
		"Noble-Payments.clarkinet.com",
		"NonWSSTime",
		"Nuget Server",
		"Onboarding .net",
		"Opserver",
		"Order Routing",
		"Order Routing Old",
		"Overseer",
		"Payment Gateway API",
		"P-Card Administration",
		"Post Order Processing",
		"QA - Regression Suite",
		"QA BA Documentation",
		"QA Sandbox",
		"QA-Webstaurantstore Projects",
		"QuizApp",
		"Rebates",
		"Release Manager",
		"Resource and Personnel Requisitions",
		"Scrum Template Sandbox",
		"SiteMetaData",
		"Shipping Calculator",
		"ShoppingCart",
		"SPS",
		"SPS .NET Rewrite",
		"SSRS Report Viewer",
		"Sales Report",
		"Shared Build and Deployment Scripts",
		"Shared JavaScript Components",
		"Shoeleather Marketing",
		"Status Check",
		"Switchboard",
		"TimeClock",
		"Timekeep",
		"Tools",
		"Transactions",
		"Triton",
		"TRS",
		"TRS API - Archived",
		"Tampa Internship",
		"Tax Exempt",
		"Tax Rate Service",
		"Telegram",
		"Test",
		"Ticket Report",
		"TicketCreator",
		"Time Off",
		"Token Machine",
		"TomHanks",
		"Tracking Notifications",
		"Vendor List",
		"Video Training",
		"WSS Chrome Extension",
		"WSS IDS Consumers",
		"Warehouse Portal",
		"Weekend Scheduler",
		"Web Notifications",
		"WebOpsDockerImages",
		"WebStats Dashboard",
		"Webstaurant URL Shortener",
		"Webstaurant.StoreFront",
		"Webstaurantstore Administration Portal",
		"Webstaurantstore Notifications",
		"Webstaurantstore QA",
		"Webstaurantstore.com",
		"XYZ",
		"iOS Connect",
		"v8eval (Internal)"
	]

	static notLinkedTcsQuery = """
SELECT Project.ProjectName, Tester.UserName, Work.WorkItemId 
FROM [AnalyticsModel].[vw_WorkItem] AS Work
LEFT JOIN [AnalyticsModel].[vw_WorkItemLink] AS Link ON Work.WorkItemId = Link.TargetWorkItemId
LEFT JOIN [AnalyticsModel].[vw_Project] AS Project ON Work.ProjectSK = Project.ProjectSK
LEFT JOIN [AnalyticsModel].[vw_User] AS Tester ON Work.AssignedToUserSK = Tester.UserSK
WHERE Work.WorkItemType = 'Test Case'
AND Link.TargetWorkItemId IS NULL
"""


	// Get Projects List
	synchronized static getAll() {
		return AzureDevOpsTestPlans.apiCall("https://tfs.clarkinc.biz/DefaultCollection/_apis/projects?api-version=5.0").value.collect{it.name}.sort()
	}


}
